[package]
name = "merlin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.6.0"
console = "0.15.8"
csv = "1.3.0"
lazy_static = "1.4.0"
nom = "7.1.3"
